service: portfolio-contact-services

package:
  individually: true
  
provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  stage: ${opt:stage, "dev"}

plugins:
  - serverless-offline
  - serverless-python-requirements
  - serverless-dotenv-plugin

custom:
  pythonRequirements:
    dockerizePip: true
    usePoetry: true
  dotenv:
    path: ./.env
    dotenvParser: dotenv.config.js

functions:
  app:
    handler: lambda.handler
    package:
      patterns:
        - .env-local
    events:
      - http:
          method: any
          path: / 
      - http:
          method: any
          path: /{proxy+}