service: portfolio-contact-services

package:
  individually: true
  exclude:
    - .venv/**
    - .git/**
    - .scripts/**
    - node_modules/**
    - tests/**
    - scripts.py
  
provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  stage: ${opt:stage, "dev"}

plugins:
  - serverless-offline
  - serverless-python-requirements
  - serverless-dotenv-plugin

custom:
  pythonRequirements:
    dockerizePip: true
    usePoetry: true
  dotenv:
    path: ./.env-prod
    dotenvParser: dotenv.config.js

functions:
  app:
    handler: lambda.handler
    events:
      - http:
          method: any
          path: / 
      - http:
          method: any
          path: /{proxy+}