service: portfolio-email-services

package:
  individually: true
  
provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  stage: ${opt:stage, "dev"}

plugins:
  - serverless-offline
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    usePoetry: true

functions:
  app:
    handler: lambda.handler
    environment: 
      EMAIL: oscarkaka222@gmail.com
      PASSWORD: dyqwducdroumngxo
      MONGO_CONNECTION_STR: mongodb+srv://oscar:oscar@cluster0.xlh9q.gcp.mongodb.net
      MONGO_DB_NAME: portfolio
      MONGO_DB_COLLECTION: contacts
    events:
      - http:
          method: any
          path: / 
      - http:
          method: any
          path: /{proxy+}